export const listOfBloodGroup = [
  { name: "A+", id: "A+" },
  { name: "A-", id: "A-" },
  { name: "B+", id: "B+" },
  { name: "B-", id: "B-" },
  { name: "AB+", id: "AB+" },
  { name: "AB-", id: "AB-" },
  { name: "O+", id: "O+" },
  { name: "O-", id: "O-" },
];

export const areaLocation = [
  { name: "Abdullahpur", id: "Abdullahpur" },
  { name: "Uttara", id: "Uttara" },
  { name: "Mirpur", id: "Mirpur" },
  { name: "Pallabi", id: "Pallabi" },
  { name: "Kazipara", id: "Kazipara" },
  { name: "Kafrul", id: "Kafrul" },
  { name: "Agargaon", id: "Agargaon" },
  { name: "Cantonment", id: "Cantonment" },
  { name: "Banani", id: "Banani" },
  { name: "Gulshan", id: "Gulshan" },
  { name: "Mohakhali", id: "Mohakhali" },
  { name: "Bashundhara", id: "Bashundhara" },
  { name: "Banasree", id: "Banasree" },
  { name: "Baridhara", id: "Baridhara" },
  { name: "Tejgaon", id: "Tejgaon" },
  { name: "Farmgate", id: "Farmgate" },
  { name: "Mohammadpur", id: "Mohammadpur" },
  { name: "Rampura", id: "Rampura" },
  { name: "Khilgaon", id: "Khilgaon" },
  { name: "Gabtali", id: "Gabtali" },
  { name: "Hazaribagh", id: "Hazaribagh" },
  { name: "Dhanmondi", id: "Dhanmondi" },
  { name: "Ramna", id: "Ramna" },
  { name: "Motijheel", id: "Motijheel" },
  { name: "Lalbagh", id: "Lalbagh" },
  { name: "Kamalapur", id: "Kamalapur" },
  { name: "Sadarghat", id: "Sadarghat" },
  { name: "Wari", id: "Wari" },
  { name: "Demra", id: "Demra" },
  { name: "Matuail", id: "Matuail" },
  { name: "Shahbagh", id: "Shahbagh" },
  { name: "Paltan", id: "Paltan" },
];
